---
# https://www.mongodb.com/docs/manual/tutorial/install-mongodb-on-ubuntu/
- hosts: database
  tasks:
    - name: Import the MongoDB public key used by the package management system
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-7.0.asc
        keyring: /usr/share/keyrings/mongodb-server-7.0.gpg
        state: present
      become: true
      become_user: root

    - name: Add MongoDB repository to sources list
      shell: echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-7.0.gpg ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/7.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-7.0.list

    - name: Install the MongoDB packages
      ansible.builtin.apt:
        name:
          - mongodb-org=7.0.12
          - mongodb-org-database=7.0.12
          - mongodb-org-server=7.0.12
          - mongodb-mongosh=2.0.1
          - mongodb-org-mongos=7.0.12
          - mongodb-org-tools=7.0.12
        state: present
        update_cache: yes
      become: true
      become_user: root
